### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by fquiroz** [chat21/chat21-web-widget#23]
environment:
`npm -v = 6.13.4`
`node -v = v12.16.1`
`OS: macOS`
 
i've installed cloud functions , create a firebase database.

` git clone git clone https://github.com/chat21/chat21-web-widget.git`
`npm install`
and i got errors:

n=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/fer/Documents/desarrollo/javascript/chat21-web-widget/node_modules/grpc
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/fer/Documents/desarrollo/javascript/chat21-web-widget/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/fer/Documents/desarrollo/javascript/chat21-web-widget/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/fer/Documents/desarrollo/javascript/chat21-web-widget/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/fer/Documents/desarrollo/javascript/chat21-web-widget/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/fer/Documents/desarrollo/javascript/chat21-web-widget/node_modules/grpc
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/fer/Documents/desarrollo/javascript/chat21-web-widget/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/fer/Documents/desarrollo/javascript/chat21-web-widget/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-resize-event@0.4.4 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.18.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.18.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by peterwangxw** [comment]
The same here

**Comment by andrealeo83** [comment]
It is related to a Firebase issue with node 12: https://github.com/firebase/firebase-js-sdk/issues/1738 Downgrade node to 10 or 11

**Comment by cofimate** [comment]
Andrea, since  there this issue with the firebase package that we need to restrict to Node 10 or 11 what would the Angular CLI version proper to run in the desktop ?
Grazie mile per tu lavoro

**Comment by andrealeo83** [comment]
![image](https://user-images.githubusercontent.com/9378770/118941063-a19f6700-b951-11eb-9fc7-e5a9ebba5f27.png)
This is my configuration for the widget

**Comment by andrealeo83** [comment]
But also work with Node 12. Can you confirm?
![image](https://user-images.githubusercontent.com/9378770/118945899-3015e780-b956-11eb-8f73-0b42e232ceef.png)
